# Расширенная база продуктов для HealthAI
# Более 200 продуктов в различных категориях

PRODUCTS = [
    # === ОВОЩИ (30 продуктов) ===
    {"name": "Баклажан", "category": "vegetables", "calories": 25, "protein": 1.2, "fat": 0.2, "carbs": 4.5, "fiber": 3.0, "sugar": 3.2, "glycemic_index": 10, "is_healthy": True},
    {"name": "Кабачок", "category": "vegetables", "calories": 24, "protein": 1.1, "fat": 0.3, "carbs": 4.6, "fiber": 1.0, "sugar": 2.5, "glycemic_index": 15, "is_healthy": True},
    {"name": "Огурец", "category": "vegetables", "calories": 15, "protein": 0.8, "fat": 0.1, "carbs": 3.0, "fiber": 0.5, "sugar": 1.7, "glycemic_index": 15, "is_healthy": True},
    {"name": "Помидор", "category": "vegetables", "calories": 20, "protein": 1.1, "fat": 0.2, "carbs": 3.7, "fiber": 1.2, "sugar": 2.6, "glycemic_index": 10, "is_healthy": True},
    {"name": "Перец болгарский красный", "category": "vegetables", "calories": 31, "protein": 1.0, "fat": 0.3, "carbs": 6.0, "fiber": 1.9, "sugar": 4.2, "glycemic_index": 15, "is_healthy": True},
    {"name": "Перец болгарский желтый", "category": "vegetables", "calories": 27, "protein": 1.0, "fat": 0.2, "carbs": 5.3, "fiber": 1.3, "sugar": 3.5, "glycemic_index": 15, "is_healthy": True},
    {"name": "Морковь", "category": "vegetables", "calories": 41, "protein": 0.9, "fat": 0.2, "carbs": 9.6, "fiber": 2.8, "sugar": 4.7, "glycemic_index": 35, "is_healthy": True},
    {"name": "Свёкла", "category": "vegetables", "calories": 43, "protein": 1.6, "fat": 0.2, "carbs": 9.6, "fiber": 2.8, "sugar": 6.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Капуста белокочанная", "category": "vegetables", "calories": 25, "protein": 1.8, "fat": 0.1, "carbs": 4.7, "fiber": 2.0, "sugar": 3.2, "glycemic_index": 10, "is_healthy": True},
    {"name": "Капуста брокколи", "category": "vegetables", "calories": 34, "protein": 2.8, "fat": 0.4, "carbs": 6.6, "fiber": 2.6, "sugar": 1.7, "glycemic_index": 10, "is_healthy": True},
    {"name": "Капуста цветная", "category": "vegetables", "calories": 25, "protein": 1.9, "fat": 0.3, "carbs": 5.0, "fiber": 2.0, "sugar": 1.9, "glycemic_index": 15, "is_healthy": True},
    {"name": "Капуста брюссельская", "category": "vegetables", "calories": 43, "protein": 3.4, "fat": 0.3, "carbs": 8.9, "fiber": 3.8, "sugar": 2.2, "glycemic_index": 15, "is_healthy": True},
    {"name": "Шпинат", "category": "vegetables", "calories": 23, "protein": 2.9, "fat": 0.4, "carbs": 3.6, "fiber": 2.2, "sugar": 0.4, "glycemic_index": 15, "is_healthy": True},
    {"name": "Салат листовой", "category": "vegetables", "calories": 15, "protein": 1.4, "fat": 0.2, "carbs": 2.9, "fiber": 1.3, "sugar": 0.8, "glycemic_index": 10, "is_healthy": True},
    {"name": "Руккола", "category": "vegetables", "calories": 25, "protein": 2.6, "fat": 0.7, "carbs": 2.1, "fiber": 1.6, "sugar": 0.5, "glycemic_index": 10, "is_healthy": True},
    {"name": "Сельдерей стебель", "category": "vegetables", "calories": 16, "protein": 0.7, "fat": 0.2, "carbs": 3.0, "fiber": 1.6, "sugar": 1.3, "glycemic_index": 15, "is_healthy": True},
    {"name": "Спаржа", "category": "vegetables", "calories": 20, "protein": 2.2, "fat": 0.1, "carbs": 3.9, "fiber": 2.1, "sugar": 1.9, "glycemic_index": 15, "is_healthy": True},
    {"name": "Артишок", "category": "vegetables", "calories": 47, "protein": 3.3, "fat": 0.2, "carbs": 10.5, "fiber": 5.4, "sugar": 0.9, "glycemic_index": 15, "is_healthy": True},
    {"name": "Лук репчатый", "category": "vegetables", "calories": 40, "protein": 1.4, "fat": 0.1, "carbs": 9.3, "fiber": 1.7, "sugar": 4.2, "glycemic_index": 10, "is_healthy": True},
    {"name": "Лук зелёный", "category": "vegetables", "calories": 32, "protein": 1.8, "fat": 0.2, "carbs": 7.3, "fiber": 2.6, "sugar": 2.3, "glycemic_index": 10, "is_healthy": True},
    {"name": "Чеснок", "category": "vegetables", "calories": 149, "protein": 6.4, "fat": 0.5, "carbs": 33.1, "fiber": 2.1, "sugar": 1.0, "glycemic_index": 30, "is_healthy": True},
    {"name": "Тыква", "category": "vegetables", "calories": 26, "protein": 1.0, "fat": 0.1, "carbs": 6.5, "fiber": 0.5, "sugar": 2.8, "glycemic_index": 75, "is_healthy": True},
    {"name": "Картофель", "category": "vegetables", "calories": 77, "protein": 2.0, "fat": 0.1, "carbs": 17.5, "fiber": 2.2, "sugar": 0.8, "glycemic_index": 85, "is_healthy": False, "dangerous_for_diets": ["pevzner_9"]},
    {"name": "Батат", "category": "vegetables", "calories": 86, "protein": 1.6, "fat": 0.1, "carbs": 20.1, "fiber": 3.0, "sugar": 4.2, "glycemic_index": 50, "is_healthy": True},
    {"name": "Редис", "category": "vegetables", "calories": 16, "protein": 0.7, "fat": 0.1, "carbs": 3.4, "fiber": 1.6, "sugar": 1.9, "glycemic_index": 15, "is_healthy": True},
    {"name": "Репа", "category": "vegetables", "calories": 28, "protein": 0.9, "fat": 0.1, "carbs": 6.4, "fiber": 1.8, "sugar": 3.8, "glycemic_index": 15, "is_healthy": True},
    {"name": "Грибы шампиньоны", "category": "vegetables", "calories": 22, "protein": 3.1, "fat": 0.3, "carbs": 3.3, "fiber": 1.0, "sugar": 1.9, "glycemic_index": 10, "is_healthy": True},
    {"name": "Грибы вешенки", "category": "vegetables", "calories": 33, "protein": 3.3, "fat": 0.4, "carbs": 6.1, "fiber": 2.3, "sugar": 1.1, "glycemic_index": 15, "is_healthy": True},
    {"name": "Кукуруза сладкая", "category": "vegetables", "calories": 86, "protein": 3.2, "fat": 1.2, "carbs": 18.7, "fiber": 2.0, "sugar": 3.2, "glycemic_index": 52, "is_healthy": False},
    {"name": "Зелёный горошек", "category": "vegetables", "calories": 81, "protein": 5.4, "fat": 0.4, "carbs": 14.5, "fiber": 5.1, "sugar": 5.7, "glycemic_index": 40, "is_healthy": True},
    
    # === ФРУКТЫ И ЯГОДЫ (25 продуктов) ===
    {"name": "Яблоко", "category": "fruits", "calories": 52, "protein": 0.3, "fat": 0.2, "carbs": 13.8, "fiber": 2.4, "sugar": 10.4, "glycemic_index": 30, "is_healthy": True},
    {"name": "Банан", "category": "fruits", "calories": 89, "protein": 1.1, "fat": 0.3, "carbs": 22.8, "fiber": 2.6, "sugar": 12.2, "glycemic_index": 50, "is_healthy": True},
    {"name": "Апельсин", "category": "fruits", "calories": 47, "protein": 0.9, "fat": 0.1, "carbs": 11.8, "fiber": 2.4, "sugar": 9.4, "glycemic_index": 35, "is_healthy": True},
    {"name": "Грейпфрут", "category": "fruits", "calories": 42, "protein": 0.8, "fat": 0.1, "carbs": 10.7, "fiber": 1.6, "sugar": 6.9, "glycemic_index": 25, "is_healthy": True},
    {"name": "Лимон", "category": "fruits", "calories": 29, "protein": 1.1, "fat": 0.3, "carbs": 9.3, "fiber": 2.8, "sugar": 2.5, "glycemic_index": 20, "is_healthy": True},
    {"name": "Лайм", "category": "fruits", "calories": 30, "protein": 0.7, "fat": 0.2, "carbs": 10.5, "fiber": 2.8, "sugar": 1.7, "glycemic_index": 20, "is_healthy": True},
    {"name": "Виноград", "category": "fruits", "calories": 67, "protein": 0.6, "fat": 0.4, "carbs": 17.2, "fiber": 0.9, "sugar": 16.0, "glycemic_index": 45, "is_healthy": True},
    {"name": "Клубника", "category": "fruits", "calories": 32, "protein": 0.7, "fat": 0.3, "carbs": 7.7, "fiber": 2.0, "sugar": 4.9, "glycemic_index": 25, "is_healthy": True},
    {"name": "Малина", "category": "fruits", "calories": 52, "protein": 1.2, "fat": 0.7, "carbs": 11.9, "fiber": 6.5, "sugar": 4.4, "glycemic_index": 25, "is_healthy": True},
    {"name": "Черника", "category": "fruits", "calories": 57, "protein": 0.7, "fat": 0.3, "carbs": 14.5, "fiber": 2.4, "sugar": 10.0, "glycemic_index": 25, "is_healthy": True},
    {"name": "Голубика", "category": "fruits", "calories": 57, "protein": 0.7, "fat": 0.3, "carbs": 14.5, "fiber": 2.4, "sugar": 10.0, "glycemic_index": 25, "is_healthy": True},
    {"name": "Смородина чёрная", "category": "fruits", "calories": 44, "protein": 1.0, "fat": 0.4, "carbs": 10.2, "fiber": 4.8, "sugar": 7.0, "glycemic_index": 25, "is_healthy": True},
    {"name": "Смородина красная", "category": "fruits", "calories": 43, "protein": 0.6, "fat": 0.2, "carbs": 10.7, "fiber": 4.3, "sugar": 7.4, "glycemic_index": 25, "is_healthy": True},
    {"name": "Крыжовник", "category": "fruits", "calories": 44, "protein": 0.7, "fat": 0.2, "carbs": 10.2, "fiber": 4.3, "sugar": 8.1, "glycemic_index": 25, "is_healthy": True},
    {"name": "Вишня", "category": "fruits", "calories": 50, "protein": 1.0, "fat": 0.3, "carbs": 12.2, "fiber": 1.6, "sugar": 8.5, "glycemic_index": 22, "is_healthy": True},
    {"name": "Черешня", "category": "fruits", "calories": 50, "protein": 1.0, "fat": 0.2, "carbs": 12.3, "fiber": 1.5, "sugar": 8.5, "glycemic_index": 22, "is_healthy": True},
    {"name": "Персик", "category": "fruits", "calories": 39, "protein": 0.9, "fat": 0.3, "carbs": 9.5, "fiber": 1.5, "sugar": 8.4, "glycemic_index": 30, "is_healthy": True},
    {"name": "Нектарин", "category": "fruits", "calories": 44, "protein": 1.1, "fat": 0.3, "carbs": 10.6, "fiber": 1.7, "sugar": 8.5, "glycemic_index": 30, "is_healthy": True},
    {"name": "Абрикос", "category": "fruits", "calories": 48, "protein": 1.4, "fat": 0.4, "carbs": 11.1, "fiber": 2.0, "sugar": 9.2, "glycemic_index": 20, "is_healthy": True},
    {"name": "Слива", "category": "fruits", "calories": 46, "protein": 0.7, "fat": 0.3, "carbs": 11.4, "fiber": 1.4, "sugar": 9.9, "glycemic_index": 22, "is_healthy": True},
    {"name": "Груша", "category": "fruits", "calories": 57, "protein": 0.4, "fat": 0.1, "carbs": 15.2, "fiber": 3.1, "sugar": 9.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Киви", "category": "fruits", "calories": 61, "protein": 1.1, "fat": 0.5, "carbs": 14.7, "fiber": 3.0, "sugar": 9.0, "glycemic_index": 50, "is_healthy": True},
    {"name": "Манго", "category": "fruits", "calories": 60, "protein": 0.8, "fat": 0.4, "carbs": 15.0, "fiber": 1.6, "sugar": 13.7, "glycemic_index": 50, "is_healthy": True},
    {"name": "Ананас", "category": "fruits", "calories": 50, "protein": 0.5, "fat": 0.1, "carbs": 13.1, "fiber": 1.4, "sugar": 9.9, "glycemic_index": 45, "is_healthy": True},
    {"name": "Арбуз", "category": "fruits", "calories": 30, "protein": 0.6, "fat": 0.2, "carbs": 7.6, "fiber": 0.4, "sugar": 6.2, "glycemic_index": 72, "is_healthy": True},
    {"name": "Дыня", "category": "fruits", "calories": 34, "protein": 0.8, "fat": 0.2, "carbs": 8.2, "fiber": 0.9, "sugar": 7.9, "glycemic_index": 65, "is_healthy": True},
    
    # === МЯСО И ПТИЦА (20 продуктов) ===
    {"name": "Куриная грудка", "category": "meat", "calories": 165, "protein": 31.0, "fat": 3.6, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Куриное бедро", "category": "meat", "calories": 209, "protein": 26.0, "fat": 11.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Куриное филе", "category": "meat", "calories": 113, "protein": 23.0, "fat": 1.5, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Индейка филе", "category": "meat", "calories": 115, "protein": 24.0, "fat": 1.5, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Индейка бедро", "category": "meat", "calories": 144, "protein": 21.0, "fat": 6.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Говядина постная", "category": "meat", "calories": 158, "protein": 26.0, "fat": 5.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Говядина жирная", "category": "meat", "calories": 250, "protein": 20.0, "fat": 18.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Телятина", "category": "meat", "calories": 131, "protein": 24.0, "fat": 3.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Свинина постная", "category": "meat", "calories": 160, "protein": 26.0, "fat": 5.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Свинина жирная", "category": "meat", "calories": 300, "protein": 16.0, "fat": 25.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Баранина постная", "category": "meat", "calories": 175, "protein": 25.0, "fat": 8.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Баранина жирная", "category": "meat", "calories": 294, "protein": 17.0, "fat": 24.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Кролик", "category": "meat", "calories": 173, "protein": 25.0, "fat": 7.5, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Утка", "category": "meat", "calories": 337, "protein": 19.0, "fat": 28.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Гусь", "category": "meat", "calories": 319, "protein": 23.0, "fat": 25.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Печень говяжья", "category": "meat", "calories": 125, "protein": 20.0, "fat": 3.5, "carbs": 4.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Печень куриная", "category": "meat", "calories": 136, "protein": 20.0, "fat": 5.0, "carbs": 1.5, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Сердце говяжье", "category": "meat", "calories": 96, "protein": 16.0, "fat": 3.0, "carbs": 1.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Язык говяжий", "category": "meat", "calories": 173, "protein": 16.0, "fat": 12.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Фарш говяжий", "category": "meat", "calories": 250, "protein": 17.0, "fat": 20.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    
    # === РЫБА И МОРЕПРОДУКТЫ (25 продуктов) ===
    {"name": "Лосось", "category": "fish", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Форель", "category": "fish", "calories": 148, "protein": 20.0, "fat": 7.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Тунец свежий", "category": "fish", "calories": 144, "protein": 23.0, "fat": 5.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Тунец консервированный", "category": "fish", "calories": 116, "protein": 26.0, "fat": 1.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Сёмга", "category": "fish", "calories": 219, "protein": 20.0, "fat": 15.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Треска", "category": "fish", "calories": 82, "protein": 18.0, "fat": 0.7, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Минтай", "category": "fish", "calories": 72, "protein": 16.0, "fat": 0.7, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Хек", "category": "fish", "calories": 86, "protein": 17.0, "fat": 2.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Пикша", "category": "fish", "calories": 73, "protein": 17.0, "fat": 0.5, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Судак", "category": "fish", "calories": 84, "protein": 18.0, "fat": 1.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Щука", "category": "fish", "calories": 82, "protein": 18.0, "fat": 1.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Карп", "category": "fish", "calories": 126, "protein": 18.0, "fat": 5.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Сельдь", "category": "fish", "calories": 161, "protein": 18.0, "fat": 9.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Скумбрия", "category": "fish", "calories": 205, "protein": 19.0, "fat": 14.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Камбала", "category": "fish", "calories": 91, "protein": 18.0, "fat": 2.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Палтус", "category": "fish", "calories": 111, "protein": 19.0, "fat": 3.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Окунь морской", "category": "fish", "calories": 103, "protein": 20.0, "fat": 2.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Креветки", "category": "fish", "calories": 95, "protein": 20.0, "fat": 1.5, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Кальмары", "category": "fish", "calories": 92, "protein": 18.0, "fat": 1.4, "carbs": 3.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Мидии", "category": "fish", "calories": 86, "protein": 12.0, "fat": 2.0, "carbs": 4.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Устрицы", "category": "fish", "calories": 68, "protein": 7.0, "fat": 2.0, "carbs": 5.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Краб", "category": "fish", "calories": 87, "protein": 19.0, "fat": 1.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Осьминог", "category": "fish", "calories": 82, "protein": 15.0, "fat": 1.0, "carbs": 2.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Икра красная", "category": "fish", "calories": 263, "protein": 32.0, "fat": 14.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Икра чёрная", "category": "fish", "calories": 239, "protein": 27.0, "fat": 13.0, "carbs": 4.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    
    # === МОЛОЧНЫЕ ПРОДУКТЫ (20 продуктов) ===
    {"name": "Молоко 1%", "category": "dairy", "calories": 40, "protein": 3.4, "fat": 1.0, "carbs": 4.8, "fiber": 0.0, "sugar": 4.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Молоко 2.5%", "category": "dairy", "calories": 52, "protein": 3.2, "fat": 2.5, "carbs": 4.8, "fiber": 0.0, "sugar": 4.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Молоко 3.2%", "category": "dairy", "calories": 58, "protein": 3.0, "fat": 3.2, "carbs": 4.8, "fiber": 0.0, "sugar": 4.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Кефир 1%", "category": "dairy", "calories": 40, "protein": 3.0, "fat": 1.0, "carbs": 4.0, "fiber": 0.0, "sugar": 4.0, "glycemic_index": 25, "is_healthy": True},
    {"name": "Кефир 2.5%", "category": "dairy", "calories": 53, "protein": 2.9, "fat": 2.5, "carbs": 4.0, "fiber": 0.0, "sugar": 4.0, "glycemic_index": 25, "is_healthy": True},
    {"name": "Йогурт натуральный", "category": "dairy", "calories": 60, "protein": 4.0, "fat": 2.5, "carbs": 5.0, "fiber": 0.0, "sugar": 5.0, "glycemic_index": 25, "is_healthy": True},
    {"name": "Йогурт греческий", "category": "dairy", "calories": 59, "protein": 10.0, "fat": 0.4, "carbs": 3.6, "fiber": 0.0, "sugar": 3.2, "glycemic_index": 20, "is_healthy": True},
    {"name": "Творог обезжиренный", "category": "dairy", "calories": 72, "protein": 18.0, "fat": 0.0, "carbs": 1.8, "fiber": 0.0, "sugar": 1.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Творог 2%", "category": "dairy", "calories": 103, "protein": 18.0, "fat": 2.0, "carbs": 1.8, "fiber": 0.0, "sugar": 1.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Творог 5%", "category": "dairy", "calories": 121, "protein": 17.0, "fat": 5.0, "carbs": 1.8, "fiber": 0.0, "sugar": 1.8, "glycemic_index": 30, "is_healthy": True},
    {"name": "Творог 9%", "category": "dairy", "calories": 159, "protein": 16.0, "fat": 9.0, "carbs": 2.0, "fiber": 0.0, "sugar": 2.0, "glycemic_index": 30, "is_healthy": True},
    {"name": "Сыр творожный", "category": "dairy", "calories": 160, "protein": 14.0, "fat": 9.0, "carbs": 4.0, "fiber": 0.0, "sugar": 3.0, "glycemic_index": 30, "is_healthy": True},
    {"name": "Сыр моцарелла", "category": "dairy", "calories": 280, "protein": 28.0, "fat": 18.0, "carbs": 2.0, "fiber": 0.0, "sugar": 1.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Сыр чеддер", "category": "dairy", "calories": 403, "protein": 25.0, "fat": 33.0, "carbs": 1.3, "fiber": 0.0, "sugar": 0.5, "glycemic_index": 0, "is_healthy": False},
    {"name": "Сыр пармезан", "category": "dairy", "calories": 431, "protein": 38.0, "fat": 29.0, "carbs": 4.0, "fiber": 0.0, "sugar": 0.9, "glycemic_index": 0, "is_healthy": False},
    {"name": "Сыр фета", "category": "dairy", "calories": 264, "protein": 14.0, "fat": 21.0, "carbs": 4.0, "fiber": 0.0, "sugar": 4.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Сыр сулугуни", "category": "dairy", "calories": 285, "protein": 20.0, "fat": 22.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Сметана 10%", "category": "dairy", "calories": 115, "protein": 3.0, "fat": 10.0, "carbs": 3.0, "fiber": 0.0, "sugar": 3.0, "glycemic_index": 30, "is_healthy": True},
    {"name": "Сметана 20%", "category": "dairy", "calories": 206, "protein": 2.8, "fat": 20.0, "carbs": 3.2, "fiber": 0.0, "sugar": 3.2, "glycemic_index": 30, "is_healthy": False},
    {"name": "Сливки 10%", "category": "dairy", "calories": 118, "protein": 3.0, "fat": 10.0, "carbs": 4.0, "fiber": 0.0, "sugar": 4.0, "glycemic_index": 30, "is_healthy": True},
    
    # === КРУПЫ И ЗЛАКИ (20 продуктов) ===
    {"name": "Гречка варёная", "category": "grains", "calories": 110, "protein": 4.2, "fat": 1.1, "carbs": 21.3, "fiber": 3.3, "sugar": 0.5, "glycemic_index": 50, "is_healthy": True},
    {"name": "Рис белый варёный", "category": "grains", "calories": 130, "protein": 2.7, "fat": 0.3, "carbs": 28.0, "fiber": 0.4, "sugar": 0.1, "glycemic_index": 70, "is_healthy": False},
    {"name": "Рис бурый варёный", "category": "grains", "calories": 112, "protein": 2.6, "fat": 0.9, "carbs": 23.0, "fiber": 1.8, "sugar": 0.4, "glycemic_index": 50, "is_healthy": True},
    {"name": "Овсянка на воде", "category": "grains", "calories": 88, "protein": 3.0, "fat": 1.7, "carbs": 15.0, "fiber": 2.0, "sugar": 0.5, "glycemic_index": 40, "is_healthy": True},
    {"name": "Овсянка на молоке", "category": "grains", "calories": 102, "protein": 4.0, "fat": 2.5, "carbs": 15.0, "fiber": 2.0, "sugar": 4.0, "glycemic_index": 45, "is_healthy": True},
    {"name": "Перловка варёная", "category": "grains", "calories": 109, "protein": 2.3, "fat": 0.5, "carbs": 24.0, "fiber": 3.8, "sugar": 0.3, "glycemic_index": 25, "is_healthy": True},
    {"name": "Ячневая каша", "category": "grains", "calories": 76, "protein": 2.3, "fat": 0.3, "carbs": 15.7, "fiber": 3.0, "sugar": 0.2, "glycemic_index": 35, "is_healthy": True},
    {"name": "Пшённая каша", "category": "grains", "calories": 90, "protein": 3.0, "fat": 1.0, "carbs": 17.0, "fiber": 1.0, "sugar": 0.2, "glycemic_index": 40, "is_healthy": True},
    {"name": "Манная каша", "category": "grains", "calories": 100, "protein": 3.0, "fat": 1.5, "carbs": 18.0, "fiber": 0.5, "sugar": 1.0, "glycemic_index": 65, "is_healthy": False},
    {"name": "Кукурузная каша", "category": "grains", "calories": 86, "protein": 2.0, "fat": 0.5, "carbs": 18.0, "fiber": 2.0, "sugar": 0.3, "glycemic_index": 40, "is_healthy": True},
    {"name": "Киноа варёная", "category": "grains", "calories": 120, "protein": 4.4, "fat": 1.9, "carbs": 21.3, "fiber": 2.8, "sugar": 0.9, "glycemic_index": 35, "is_healthy": True},
    {"name": "Бульгур варёный", "category": "grains", "calories": 83, "protein": 3.1, "fat": 0.2, "carbs": 19.0, "fiber": 4.5, "sugar": 0.1, "glycemic_index": 45, "is_healthy": True},
    {"name": "Кускус варёный", "category": "grains", "calories": 112, "protein": 3.8, "fat": 0.2, "carbs": 23.0, "fiber": 1.4, "sugar": 0.2, "glycemic_index": 60, "is_healthy": True},
    {"name": "Макароны твёрдых сортов", "category": "grains", "calories": 157, "protein": 5.0, "fat": 1.0, "carbs": 31.0, "fiber": 3.0, "sugar": 0.6, "glycemic_index": 50, "is_healthy": True},
    {"name": "Макароны обычные", "category": "grains", "calories": 157, "protein": 5.0, "fat": 1.0, "carbs": 31.0, "fiber": 1.5, "sugar": 0.6, "glycemic_index": 60, "is_healthy": False},
    {"name": "Хлеб белый", "category": "grains", "calories": 265, "protein": 8.0, "fat": 3.0, "carbs": 50.0, "fiber": 2.5, "sugar": 5.0, "glycemic_index": 75, "is_healthy": False},
    {"name": "Хлеб чёрный", "category": "grains", "calories": 259, "protein": 8.5, "fat": 3.5, "carbs": 47.0, "fiber": 5.0, "sugar": 4.0, "glycemic_index": 65, "is_healthy": True},
    {"name": "Хлеб цельнозерновой", "category": "grains", "calories": 240, "protein": 10.0, "fat": 4.0, "carbs": 40.0, "fiber": 7.0, "sugar": 3.0, "glycemic_index": 50, "is_healthy": True},
    {"name": "Хлеб ржаной", "category": "grains", "calories": 259, "protein": 8.0, "fat": 2.5, "carbs": 48.0, "fiber": 6.0, "sugar": 3.5, "glycemic_index": 55, "is_healthy": True},
    {"name": "Хлебцы цельнозерновые", "category": "grains", "calories": 310, "protein": 11.0, "fat": 3.0, "carbs": 58.0, "fiber": 10.0, "sugar": 1.0, "glycemic_index": 45, "is_healthy": True},
    
    # === БОБОВЫЕ (10 продуктов) ===
    {"name": "Фасоль красная варёная", "category": "legumes", "calories": 127, "protein": 8.7, "fat": 0.5, "carbs": 22.8, "fiber": 6.4, "sugar": 0.3, "glycemic_index": 25, "is_healthy": True},
    {"name": "Фасоль белая варёная", "category": "legumes", "calories": 139, "protein": 9.7, "fat": 0.4, "carbs": 25.1, "fiber": 6.3, "sugar": 0.3, "glycemic_index": 25, "is_healthy": True},
    {"name": "Нут варёный", "category": "legumes", "calories": 164, "protein": 8.9, "fat": 2.6, "carbs": 27.4, "fiber": 7.6, "sugar": 4.8, "glycemic_index": 28, "is_healthy": True},
    {"name": "Чечевица красная варёная", "category": "legumes", "calories": 116, "protein": 9.0, "fat": 0.4, "carbs": 20.1, "fiber": 7.9, "sugar": 1.8, "glycemic_index": 25, "is_healthy": True},
    {"name": "Чечевица зелёная варёная", "category": "legumes", "calories": 116, "protein": 9.0, "fat": 0.4, "carbs": 20.1, "fiber": 7.9, "sugar": 1.8, "glycemic_index": 25, "is_healthy": True},
    {"name": "Горох варёный", "category": "legumes", "calories": 118, "protein": 8.3, "fat": 0.4, "carbs": 21.1, "fiber": 8.3, "sugar": 3.0, "glycemic_index": 25, "is_healthy": True},
    {"name": "Соя варёная", "category": "legumes", "calories": 173, "protein": 16.6, "fat": 9.0, "carbs": 9.9, "fiber": 6.0, "sugar": 3.0, "glycemic_index": 15, "is_healthy": True},
    {"name": "Тофу", "category": "legumes", "calories": 76, "protein": 8.0, "fat": 4.8, "carbs": 1.9, "fiber": 0.3, "sugar": 0.7, "glycemic_index": 15, "is_healthy": True},
    {"name": "Темпе", "category": "legumes", "calories": 193, "protein": 19.0, "fat": 11.0, "carbs": 9.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 20, "is_healthy": True},
    {"name": "Эдамаме", "category": "legumes", "calories": 122, "protein": 11.0, "fat": 5.0, "carbs": 10.0, "fiber": 5.0, "sugar": 2.2, "glycemic_index": 15, "is_healthy": True},
    
    # === ОРЕХИ И СЕМЕНА (15 продуктов) ===
    {"name": "Миндаль", "category": "nuts", "calories": 579, "protein": 21.0, "fat": 50.0, "carbs": 22.0, "fiber": 12.0, "sugar": 4.4, "glycemic_index": 15, "is_healthy": True},
    {"name": "Грецкий орех", "category": "nuts", "calories": 654, "protein": 15.0, "fat": 65.0, "carbs": 14.0, "fiber": 7.0, "sugar": 2.6, "glycemic_index": 15, "is_healthy": True},
    {"name": "Фундук", "category": "nuts", "calories": 628, "protein": 15.0, "fat": 61.0, "carbs": 17.0, "fiber": 10.0, "sugar": 4.3, "glycemic_index": 15, "is_healthy": True},
    {"name": "Кешью", "category": "nuts", "calories": 553, "protein": 18.0, "fat": 44.0, "carbs": 30.0, "fiber": 3.3, "sugar": 6.0, "glycemic_index": 22, "is_healthy": True},
    {"name": "Фисташки", "category": "nuts", "calories": 560, "protein": 20.0, "fat": 45.0, "carbs": 27.0, "fiber": 10.0, "sugar": 7.7, "glycemic_index": 15, "is_healthy": True},
    {"name": "Арахис", "category": "nuts", "calories": 567, "protein": 26.0, "fat": 49.0, "carbs": 16.0, "fiber": 8.0, "sugar": 4.0, "glycemic_index": 13, "is_healthy": True},
    {"name": "Бразильский орех", "category": "nuts", "calories": 659, "protein": 14.0, "fat": 67.0, "carbs": 12.0, "fiber": 7.5, "sugar": 2.3, "glycemic_index": 10, "is_healthy": True},
    {"name": "Кедровые орехи", "category": "nuts", "calories": 673, "protein": 14.0, "fat": 68.0, "carbs": 13.0, "fiber": 3.7, "sugar": 3.6, "glycemic_index": 15, "is_healthy": True},
    {"name": "Макадамия", "category": "nuts", "calories": 718, "protein": 8.0, "fat": 76.0, "carbs": 14.0, "fiber": 9.0, "sugar": 4.6, "glycemic_index": 10, "is_healthy": True},
    {"name": "Семена подсолнечника", "category": "nuts", "calories": 584, "protein": 21.0, "fat": 51.0, "carbs": 20.0, "fiber": 9.0, "sugar": 2.6, "glycemic_index": 15, "is_healthy": True},
    {"name": "Семена тыквы", "category": "nuts", "calories": 559, "protein": 30.0, "fat": 49.0, "carbs": 15.0, "fiber": 6.0, "sugar": 1.4, "glycemic_index": 10, "is_healthy": True},
    {"name": "Семена льна", "category": "nuts", "calories": 534, "protein": 18.0, "fat": 42.0, "carbs": 29.0, "fiber": 27.0, "sugar": 1.6, "glycemic_index": 10, "is_healthy": True},
    {"name": "Семена чиа", "category": "nuts", "calories": 486, "protein": 17.0, "fat": 31.0, "carbs": 42.0, "fiber": 34.0, "sugar": 0.0, "glycemic_index": 1, "is_healthy": True},
    {"name": "Кунжут", "category": "nuts", "calories": 573, "protein": 18.0, "fat": 49.0, "carbs": 23.0, "fiber": 12.0, "sugar": 0.3, "glycemic_index": 15, "is_healthy": True},
    {"name": "Мак", "category": "nuts", "calories": 525, "protein": 18.0, "fat": 44.0, "carbs": 28.0, "fiber": 20.0, "sugar": 3.0, "glycemic_index": 10, "is_healthy": True},
    
    # === МАСЛА И ЖИРЫ (10 продуктов) ===
    {"name": "Масло оливковое", "category": "oils", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Масло подсолнечное", "category": "oils", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Масло кокосовое", "category": "oils", "calories": 862, "protein": 0.0, "fat": 100.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Масло льняное", "category": "oils", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Масло сливочное", "category": "oils", "calories": 717, "protein": 0.9, "fat": 81.0, "carbs": 0.1, "fiber": 0.0, "sugar": 0.1, "glycemic_index": 0, "is_healthy": False},
    {"name": "Масло топлёное", "category": "oils", "calories": 876, "protein": 0.3, "fat": 99.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Маргарин", "category": "oils", "calories": 717, "protein": 0.2, "fat": 80.0, "carbs": 0.7, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Сало", "category": "oils", "calories": 815, "protein": 2.4, "fat": 90.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Жир животный", "category": "oils", "calories": 897, "protein": 0.0, "fat": 100.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": False},
    {"name": "Майонез", "category": "oils", "calories": 680, "protein": 1.0, "fat": 75.0, "carbs": 3.0, "fiber": 0.0, "sugar": 2.5, "glycemic_index": 15, "is_healthy": False},
    
    # === СЛАДОСТИ И КОНДИТЕРСКИЕ ИЗДЕЛИЯ (15 продуктов) ===
    {"name": "Сахар белый", "category": "sweets", "calories": 387, "protein": 0.0, "fat": 0.0, "carbs": 100.0, "fiber": 0.0, "sugar": 100.0, "glycemic_index": 65, "is_healthy": False, "is_dangerous": True, "dangerous_for_diets": ["pevzner_9"]},
    {"name": "Сахар коричневый", "category": "sweets", "calories": 377, "protein": 0.0, "fat": 0.0, "carbs": 97.0, "fiber": 0.0, "sugar": 97.0, "glycemic_index": 65, "is_healthy": False},
    {"name": "Мёд", "category": "sweets", "calories": 304, "protein": 0.3, "fat": 0.0, "carbs": 82.0, "fiber": 0.2, "sugar": 82.0, "glycemic_index": 55, "is_healthy": True},
    {"name": "Шоколад тёмный", "category": "sweets", "calories": 546, "protein": 5.5, "fat": 31.0, "carbs": 59.0, "fiber": 7.0, "sugar": 48.0, "glycemic_index": 20, "is_healthy": True},
    {"name": "Шоколад молочный", "category": "sweets", "calories": 535, "protein": 7.0, "fat": 30.0, "carbs": 59.0, "fiber": 3.0, "sugar": 52.0, "glycemic_index": 45, "is_healthy": False},
    {"name": "Шоколад белый", "category": "sweets", "calories": 539, "protein": 6.0, "fat": 30.0, "carbs": 59.0, "fiber": 1.0, "sugar": 59.0, "glycemic_index": 50, "is_healthy": False},
    {"name": "Конфеты карамель", "category": "sweets", "calories": 380, "protein": 0.5, "fat": 0.3, "carbs": 95.0, "fiber": 0.0, "sugar": 80.0, "glycemic_index": 70, "is_healthy": False},
    {"name": "Конфеты шоколадные", "category": "sweets", "calories": 500, "protein": 5.0, "fat": 25.0, "carbs": 65.0, "fiber": 2.0, "sugar": 55.0, "glycemic_index": 50, "is_healthy": False},
    {"name": "Печенье овсяное", "category": "sweets", "calories": 437, "protein": 6.5, "fat": 14.0, "carbs": 71.0, "fiber": 4.0, "sugar": 25.0, "glycemic_index": 55, "is_healthy": False},
    {"name": "Печенье песочное", "category": "sweets", "calories": 460, "protein": 6.0, "fat": 20.0, "carbs": 65.0, "fiber": 1.5, "sugar": 30.0, "glycemic_index": 60, "is_healthy": False},
    {"name": "Торт бисквитный", "category": "sweets", "calories": 350, "protein": 5.0, "fat": 15.0, "carbs": 50.0, "fiber": 1.0, "sugar": 35.0, "glycemic_index": 60, "is_healthy": False},
    {"name": "Пирожное заварное", "category": "sweets", "calories": 380, "protein": 5.5, "fat": 20.0, "carbs": 45.0, "fiber": 0.5, "sugar": 30.0, "glycemic_index": 55, "is_healthy": False},
    {"name": "Мороженое пломбир", "category": "sweets", "calories": 207, "protein": 3.5, "fat": 11.0, "carbs": 24.0, "fiber": 0.5, "sugar": 22.0, "glycemic_index": 60, "is_healthy": False},
    {"name": "Зефир", "category": "sweets", "calories": 304, "protein": 0.8, "fat": 0.0, "carbs": 78.0, "fiber": 0.0, "sugar": 65.0, "glycemic_index": 55, "is_healthy": False},
    {"name": "Пастила", "category": "sweets", "calories": 310, "protein": 0.5, "fat": 0.0, "carbs": 80.0, "fiber": 0.5, "sugar": 65.0, "glycemic_index": 55, "is_healthy": False},
    
    # === НАПИТКИ (15 продуктов) ===
    {"name": "Вода", "category": "beverages", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Чай зелёный", "category": "beverages", "calories": 1, "protein": 0.0, "fat": 0.0, "carbs": 0.2, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Чай чёрный", "category": "beverages", "calories": 1, "protein": 0.0, "fat": 0.0, "carbs": 0.2, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Кофе чёрный", "category": "beverages", "calories": 2, "protein": 0.3, "fat": 0.0, "carbs": 0.0, "fiber": 0.0, "sugar": 0.0, "glycemic_index": 0, "is_healthy": True},
    {"name": "Кофе с молоком", "category": "beverages", "calories": 40, "protein": 2.0, "fat": 1.5, "carbs": 5.0, "fiber": 0.0, "sugar": 5.0, "glycemic_index": 30, "is_healthy": True},
    {"name": "Какао на молоке", "category": "beverages", "calories": 95, "protein": 4.0, "fat": 3.0, "carbs": 13.0, "fiber": 1.5, "sugar": 10.0, "glycemic_index": 40, "is_healthy": True},
    {"name": "Сок апельсиновый", "category": "beverages", "calories": 45, "protein": 0.7, "fat": 0.2, "carbs": 10.4, "fiber": 0.2, "sugar": 8.4, "glycemic_index": 50, "is_healthy": True},
    {"name": "Сок яблочный", "category": "beverages", "calories": 46, "protein": 0.1, "fat": 0.1, "carbs": 11.3, "fiber": 0.2, "sugar": 9.6, "glycemic_index": 40, "is_healthy": True},
    {"name": "Сок томатный", "category": "beverages", "calories": 18, "protein": 0.9, "fat": 0.1, "carbs": 3.7, "fiber": 0.4, "sugar": 2.6, "glycemic_index": 15, "is_healthy": True},
    {"name": "Сок морковный", "category": "beverages", "calories": 39, "protein": 0.9, "fat": 0.2, "carbs": 9.0, "fiber": 0.4, "sugar": 7.0, "glycemic_index": 40, "is_healthy": True},
    {"name": "Газировка сладкая", "category": "beverages", "calories": 42, "protein": 0.0, "fat": 0.0, "carbs": 11.0, "fiber": 0.0, "sugar": 11.0, "glycemic_index": 60, "is_healthy": False, "is_dangerous": True},
    {"name": "Энергетик", "category": "beverages", "calories": 45, "protein": 0.0, "fat": 0.0, "carbs": 11.0, "fiber": 0.0, "sugar": 11.0, "glycemic_index": 50, "is_healthy": False},
    {"name": "Квас", "category": "beverages", "calories": 27, "protein": 0.2, "fat": 0.0, "carbs": 6.5, "fiber": 0.0, "sugar": 5.0, "glycemic_index": 30, "is_healthy": True},
    {"name": "Компот", "category": "beverages", "calories": 60, "protein": 0.2, "fat": 0.1, "carbs": 15.0, "fiber": 0.5, "sugar": 14.0, "glycemic_index": 40, "is_healthy": True},
    {"name": "Смузи фруктовый", "category": "beverages", "calories": 65, "protein": 1.0, "fat": 0.5, "carbs": 15.0, "fiber": 2.0, "sugar": 12.0, "glycemic_index": 40, "is_healthy": True},
]
